name: ready_flutter_packages

packages:
  - packages/**

scripts:
  analyze:
    run: dart run melos exec -- flutter analyze
    description: Run flutter analyze in all packages.

  test:
    run: dart run melos exec -- flutter test
    description: Run flutter test in all packages.

  format:
    run: dart run melos exec -- dart format .
    description: Format all Dart files in all packages.
